baseURL: "http://itsthompson.github.io/"
languageCode: en-us
title: Thompson's Blog
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
    main:
        - name: Archive
          url: archive/
          weight: 5
        - name: Search
          url: search/
          weight: 5
        - name: Categories
          url: categories/
          weight: 5

taxonomies:
    category: categories
    tag: tags
    series: series

params:
    env: production
    title: Thompson's Blog
    description: "A personal blog exploring the field of mainly Computer Science 
    but also Mathematics, Physics, and Economics."
    keywords: [Computer Science, Mathematics, Economics, ThompsonT]
    authors: Thompson
    defaultTheme: auto

    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    disableScrollToTop: false

    
    homeInfoParams:
        Title: Thompson's Blog
        Content: "A personal blog exploring the field of mainly Computer Science 
    but also Mathematics, Physics, and Economics."

    socialIcons:
        - name: github
          url: "https://github.com/ItsThompson/"
    
    editPost:
        URL: "https://github.com/ItsThompson/blog/blob/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

outputs:
    home:
        - HTML
        - RSS
        - JSON